add button
js-tasks-ru/htmlcss-20231222_khalhadj pull request #7
Opened 2024-01-13 14:55 UTC by khalilalhadj

2024-01-13 14:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-13 23:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-15 22:10 UTC, GSemikozov requested changes

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +_* {
глобальные сбросы на уровне компонентов никогда не описываем, можно например в normalize или main

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.container {
вспомогательные контейнер? это лишнее, в файле стилей блока должны быть классы блока, его элементов и модификаторов, и ничего лишнего

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin-right: 15px;
марджины на уровне блока не задаем, это лишнее

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family + line-height

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
а также паддингов и высоты

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__prymary {
модификаторы пишем через одно нижнее подчеркивание `_`

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 62px;
паддинги описываем один раз на уровне блока

2024-01-15 22:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2024-01-19 15:02 UTC, khalilalhadj commented on 03-lection1/01-button/button.css
> +    padding: 15px 62px;
А они ведь разные у каждой кнопки

2024-01-25 21:04 UTC, GSemikozov requested changes

2024-01-25 21:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 55px;
`15px 55px 14px` а также `height: 48px`

2025-10-13 17:10 UTC, closed without merging